# Generated by Django 4.2.28 on 2026-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField()),
            ],
            options={
                'db_table': 'curso',
            },
        ),
    ]
