# Generated by Django 4.2.28 on 2026-03-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catedratico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catedratico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
            options={
                'db_table': 'asignacion_curso',
            },
        ),
    ]
