# Generated by Django 4.2.28 on 2026-03-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alter_alumno_table'),
        ('core', '0003_asignacioncurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('asignacion_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignacioncurso')),
            ],
            options={
                'db_table': 'inscripcion_alumno',
            },
        ),
    ]
