# Generated by Django 4.2.28 on 2026-03-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscripcionalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inscripcion_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inscripcionalumno')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
    ]
